version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "08:f8:44:0f:3a:0f:ed:30:d8:ca:92:68:dd:66:69:5c"
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/Avery-Nguyen/scheduler.git master:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build